version: '3'
services:
  db:
    image: postgres
    volumes:
      - ./server/tmp/db:/var/lib/postgresql/data

  server:
    build: ./server
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 8888 -b '0.0.0.0'"
    volumes:
      - ./server:/budget-beaver
    ports:
      - "8888:8888"
    depends_on:
      - db

  client:
    container_name: client
    build: ./client
    volumes:
      - ./client:/var/www/client
    ports:
      - 3000:3000
    environment:
      - NODE_ENV=development