version: '3'
services:
  db:
    image: postgres
    volumes:
      - ./backend/tmp/db:/var/lib/postgresql/data
  
  backend:
    build: ./backend
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 8888 -b '0.0.0.0'"
    volumes:
      - ./backend:/simpleTwitterApp
    ports:
      - "8888:8888"
    depends_on:
      - db

  frontend:
    container_name: frontend
    build: ./frontend
    volumes:
      - ./frontend:/var/www/frontend
    ports:
      - 3000:3000
    environment:
      - NODE_ENV=development