FROM ruby:2.5
RUN apt-get update -qq && apt-get install -y nodejs postgresql-client
RUN mkdir /budgetBeaver
WORKDIR /budgetBeaver
COPY Gemfile /budgetBeaver/Gemfile
COPY Gemfile.lock /budgetBeaver/Gemfile.lock
RUN bundle install
COPY . /budgetBeaver

# Add a script to be executed every time the container starts.
COPY entrypoint.sh /usr/bin/
RUN chmod +x /usr/bin/entrypoint.sh
ENTRYPOINT ["entrypoint.sh"]
EXPOSE 8888

# Start the main process.
CMD ["rails", "server", "-b", "0.0.0.0"]